### PR TITLE
Arrow2 test fixes

### PR DESCRIPTION
**Pull request by Igosuki**
This fixes the json tests @houqp

### CODE REVIEW

**Comment by Igosuki** [comment]
also physical_plan::planner::tests::bad_extension_planner

**Comment by Igosuki** [comment]
The error on the sha224 test is because the new arrow2 print function prints binary data as bits in base 10 rather than hex... Frankly I think that's a mistake because it's pretty unreadable, so do we patch this in a fork of arrow2 ? https://github.com/jorgecarleitao/arrow2/blob/main/src/array/display.rs#L107

**Comment by Igosuki** [comment]
The avro tests also need access to this fix that got merged https://github.com/jorgecarleitao/arrow2/blob/main/src/io/avro/read/deserialize.rs#L99 
Since it came after the 'Chunk' migration we should really create a temporary arrow2 fork with the proper cherry picks and modifications that we need.

**Comment by houqp** [comment]
> The error on the sha224 test is because the new arrow2 print function prints binary data as bits in base 10 rather than hex... Frankly I think that's a mistake because it's pretty unreadable, so do we patch this in a fork of arrow2 ? https://github.com/jorgecarleitao/arrow2/blob/main/src/array/display.rs#L107

cc @jorgecarleitao , do you have any particular preference on this? I am leaning towards displaying hex by default in arrow2 for better readability as well.

> Since it came after the 'Chunk' migration we should really create a temporary arrow2 fork with the proper cherry picks and modifications that we need.

How about we implement the record batch abstraction within datafusion? As a temp workaround, we can also have a temp arrow2 branch with that particular avro commit cherry-picked on top of the arrow2 commit we are based on right now.

**Comment by Igosuki** [comment]
@houqp Yeah implementing RecordBatch is the way to go, I just thought it was out of scope for this PR since it will also make it harder to pull in new changes from df.

**Pull request merged**
